### ISSUE TITLE
error raised when I try to use manipulated models

### ISSUE THREAD

**Issue by bamrainboo** [intellisec/xai-backdoors#1]
When I run `python evaluate_models.py 272
` it raise a error like this:
```
Loading models...
Loaded
Loading params...
Loaded
Loading test data...
Files already downloaded and verified
Loaded
Generating explanations...
Traceback (most recent call last):
  File "evaluate_models.py", line 95, in <module>
    main()
  File "evaluate_models.py", line 91, in main
    testable_evaluate_models(attackid)
  File "evaluate_models.py", line 68, in testable_evaluate_models
    fig = plot_heatmaps(outdir, run.get_epochs(), original_model, manipulated_model, x_test, label_test, run, save=False, show=False)
  File "/home/xx/projects/xai-backdoors-main/plot/__init__.py", line 202, in plot_heatmaps
    plot_single_sample(expls[explId][i].cpu(), axs[rowClean, i * num_images_per_sample], cmap='plasma')
  File "/home/xx/projects/xai-backdoors-main/plot/__init__.py", line 277, in plot_single_sample
    ax.imshow(sample.permute(1, 2, 0), interpolation='none', cmap=cmap, alpha=alpha)
  File "/home/xx/anaconda3/envs/xaibackdoors/lib/python3.8/site-packages/matplotlib/__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/xx/anaconda3/envs/xaibackdoors/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/home/xx/anaconda3/envs/xaibackdoors/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/home/xx/anaconda3/envs/xaibackdoors/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 5626, in imshow
    im.set_data(X)
  File "/home/xx/anaconda3/envs/xaibackdoors/lib/python3.8/site-packages/matplotlib/image.py", line 698, in set_data
    raise TypeError("Invalid shape {} for image data"
TypeError: Invalid shape (32, 32, 1) for image data
```
And I tried to `print(tmp.detach().shape)` in `def plot_heatmap` and got `torch.Size([6, 1, 32, 32])`, and I have also checked the doc about [matplotlib.pyplot.imshow], it says the shapes this function supported are :
```
(M, N): an image with scalar data. The values are mapped to colors using normalization and a colormap. See parameters norm, cmap, vmin, vmax.

(M, N, 3): an image with RGB values (0-1 float or 0-255 int).

(M, N, 4): an image with RGBA values (0-1 float or 0-255 int), i.e. including transparency.
```
So, I guess that error was raised because imshow can not show heatmap directly and you need to overlay the heatmap on original image before use imshow function.

**Comment by noppelmax** [comment]
Hey @bamrainboo ,

i just tested the main branch on a fresh folder and environment, and it worked fine:
```
(xaibackdoors) max@merry:~/github/xai-backdoors$ python evaluate_models.py 272                                               
Loading models...                                                                                                                 
Loaded                                                                                                                            
Loading params...     
Loaded
Loading test data...
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to datasets/CIFAR10/cifar-10-python.tar.gz
100%|█████████████████████████████████████████████████████████████████████████| 170498071/170498071 [00:07<00:00, 23231773.09it/s]
Extracting datasets/CIFAR10/cifar-10-python.tar.gz to datasets/CIFAR10
Loaded
Generating explanations...
Generated as output/plot.png
```

The `sample.permute(1, 2, 0)` should fix the order of dimensions, which differs between torch (C,W,H) and matplotlib (W,H,C). Does it work if you just remove `permute(1,2,0)`? Maybe you did get a different version of one of the libs, in particular matplotlib? Here is my list of installed libs:
```
(xaibackdoors) max@merry:~/github/xai-backdoors$ conda list
# packages in environment at /home/max/anaconda3/envs/xaibackdoors:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
blas                      1.0                         mkl  
brotli                    1.0.9                h5eee18b_7  
brotli-bin                1.0.9                h5eee18b_7  
brotlipy                  0.7.0           py38h27cfd23_1003  
ca-certificates           2023.08.22           h06a4308_0  
certifi                   2023.7.22        py38h06a4308_0  
cffi                      1.15.1           py38h5eee18b_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
contourpy                 1.0.5            py38hdb19cb5_0  
cryptography              41.0.2           py38h22a60cf_0  
cycler                    0.11.0             pyhd3eb1b0_0  
cyrus-sasl                2.1.28               h52b45da_1  
dbus                      1.13.18              hb2f20db_0  
expat                     2.5.0                h6a678d5_0  
filelock                  3.9.0            py38h06a4308_0  
fontconfig                2.14.1               h4c34cd2_2  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               h4a9f257_0  
giflib                    5.2.1                h5eee18b_3  
glib                      2.69.1               he621ea3_2  
gmp                       6.2.1                h295c915_3  
gmpy2                     2.1.2            py38heeb90bb_0  
gst-plugins-base          1.14.1               h6a678d5_1  
gstreamer                 1.14.1               h5eee18b_1  
icu                       58.2                 he6710b0_3  
idna                      3.4              py38h06a4308_0  
importlib_resources       5.2.0              pyhd3eb1b0_1  
intel-openmp              2023.1.0         hdb19cb5_46305  
jinja2                    3.1.2            py38h06a4308_0  
jpeg                      9e                   h5eee18b_1  
kiwisolver                1.4.4            py38h6a678d5_0  
krb5                      1.20.1               h143b758_1  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libbrotlicommon           1.0.9                h5eee18b_7  
libbrotlidec              1.0.9                h5eee18b_7  
libbrotlienc              1.0.9                h5eee18b_7  
libclang                  14.0.6          default_hc6dbbc7_1  
libclang13                14.0.6          default_he11475f_1  
libcups                   2.4.2                h2d74bed_1  
libdeflate                1.17                 h5eee18b_0  
libedit                   3.1.20221030         h5eee18b_0  
libevent                  2.1.12               hdbd6064_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libllvm14                 14.0.6               hdb19cb5_3  
libpng                    1.6.39               h5eee18b_0  
libpq                     12.15                hdbd6064_1  
libprotobuf               3.20.3               he621ea3_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtiff                   4.5.1                h6a678d5_0  
libuuid                   1.41.5               h5eee18b_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
libxcb                    1.15                 h7f8727e_0  
libxkbcommon              1.0.1                h5eee18b_1  
libxml2                   2.10.4               hcbfbd50_0  
libxslt                   1.1.37               h2085143_0  
lz4-c                     1.9.4                h6a678d5_0  
markupsafe                2.1.1            py38h7f8727e_0  
matplotlib                3.7.2            py38h06a4308_0  
matplotlib-base           3.7.2            py38h1128e8f_0  
mkl                       2023.1.0         h213fc3f_46343  
mkl-service               2.4.0            py38h5eee18b_1  
mkl_fft                   1.3.6            py38h417a72b_1  
mkl_random                1.2.2            py38h417a72b_1  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.3.0            py38h06a4308_0  
munkres                   1.1.4                      py_0  
mysql                     5.7.24               h721c034_2  
ncurses                   6.4                  h6a678d5_0  
networkx                  3.1              py38h06a4308_0  
ninja                     1.10.2               h06a4308_5  
ninja-base                1.10.2               hd09550d_5  
nspr                      4.35                 h6a678d5_0  
nss                       3.89.1               h6a678d5_0  
numpy                     1.24.3           py38hf6e8229_1  
numpy-base                1.24.3           py38h060ed82_1  
openssl                   3.0.10               h7f8727e_2  
packaging                 23.1             py38h06a4308_0  
pcre                      8.45                 h295c915_0  
pillow                    9.4.0            py38h6a678d5_0  
pip                       23.2.1           py38h06a4308_0  
ply                       3.11                     py38_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 23.2.0           py38h06a4308_0  
pyparsing                 3.0.9            py38h06a4308_0  
pyqt                      5.15.7           py38h6a678d5_1  
pyqt5-sip                 12.11.0          py38h6a678d5_1  
pysocks                   1.7.1            py38h06a4308_0  
python                    3.8.17               h955ad1f_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
pytorch                   2.0.1           cpu_py38hdc00b08_0  
pytorch-msssim            1.0.0                    pypi_0    pypi
qt-main                   5.15.2               h7358343_9  
qt-webengine              5.15.9               h9ab4d14_7  
qtwebkit                  5.212                h3fafdc1_5  
readline                  8.2                  h5eee18b_0  
requests                  2.31.0           py38h06a4308_0  
setuptools                68.0.0           py38h06a4308_0  
sip                       6.6.2            py38h6a678d5_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.2               h5eee18b_0  
sympy                     1.11.1           py38h06a4308_0  
tabulate                  0.8.10           py38h06a4308_0  
tbb                       2021.8.0             hdb19cb5_0  
tk                        8.6.12               h1ccaba5_0  
toml                      0.10.2             pyhd3eb1b0_0  
torchvision               0.15.2          cpu_py38h83e0c9b_0  
tornado                   6.3.2            py38h5eee18b_0  
tqdm                      4.65.0           py38hb070fc8_0  
typing-extensions         4.7.1            py38h06a4308_0  
typing_extensions         4.7.1            py38h06a4308_0  
urllib3                   1.26.16          py38h06a4308_0  
wheel                     0.38.4           py38h06a4308_0  
xz                        5.4.2                h5eee18b_0  
zipp                      3.11.0           py38h06a4308_0  
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.5                hc292b87_0 
```

**Comment by noppelmax** [comment]
Did you manage to get it running?
